### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Thanatos07** [gary17/zfs-recompress#1]
Im a newbie sorry. Anyways tried this but i cant figure out whats wrong. Tried to change my compression from lz4 to gzip in the disk setup and wanted to use this to recompress old files. Also tried specifying a folder with --folder but same result.
root@freenas:/mnt/h101nas/USMLE Step 1 # ./zfs-recompress.sh
searching...stat: illegal option -- c
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file|handle ...]
stat: %S: bad format
./zfs-recompress.sh: line 81: --format=1597608612*: attempted assignment to non-variable (error token is "=1597608612*")

**Comment by gary17** [comment]
It seems that your version of the `stat` command does not like the `-c` option as well as possibly the `%S` format option (`fundamental block size`). You can check that with the `man stat` command. At any rate, I switched `zfs-recompress` to use long options and added a new `--compat001` option to use `df` instead of `stat` to determine disk space available. Give it a try with and without `--compat001` and let me know how it goes. **ALWAYS MAKE A BACKUP BEFORE BATCH-PROCESSING COMPUTER FILES IN ANY WAY.**

**Comment by Thanatos07** [comment]
Without --compat
root@freenas:/mnt/h101nas/USMLEStep1 # ./zfs-recompress.sh
searching...stat: illegal option -- -
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file|handle ...]
stat: illegal option -- -
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file|handle ...]
./zfs-recompress.sh: line 118: [: : integer expression expected./zfs-recompress.sh: line 128: [: : integer expression expectedcp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file ... target_directory
rm: illegal option -- -
usage: rm [-f | -i] [-dIPRrvWx] file ...
       unlink file
'/mnt/h101nas/USMLEStep1/Goljan/G_Slides/musculoskeletal2.html' replica creation failed, could not copy


With --compat

root@freenas:/mnt/h101nas/USMLEStep1 # ./zfs-recompress.sh --compat001
searching...df: unrecognized option `--output=avail'
usage: df [-b | -g | -H | -h | -k | -m | -P] [-acilnT] [-t type] [-,]
          [file | filesystem ...]
stat: illegal option -- -
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file|handle ...]
./zfs-recompress.sh: line 118: [: : integer expression expected./zfs-recompress.sh: line 128: [: : integer expression expectedcp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file ... target_directory
rm: illegal option -- -
usage: rm [-f | -i] [-dIPRrvWx] file ...
       unlink file
'/mnt/h101nas/USMLEStep1/Goljan/G_Slides/musculoskeletal2.html' replica creation failed, could not copy

**Comment by gary17** [comment]
First of all, please **do not run this script in live mode** just yet, always use the dry run mode (`--dry-run`) first.

The bad news is that your `stat` does not seem to like long command options either, the same for `df` or even `cp` and `rm` for that matter. You are running the script under FreeNAS, right? Which version, exactly? It can be found in `/etc/version` or somewhere in the FreeNAS web UI.

In order to fix this, I will have to setup FreeNAS/FreeBSD under QEMU and pretty much rewrite and retest the whole script. A fair warning: it might not be overnight before I can get this done.

Alternatively, if you can mount your storage as NAS or ZFS under a Linux installation (I use Ubuntu 20.04, ZFS 0.8.3) and run the script under Linux, it should work without any problems. If you try the ZFS route, make sure to check whether ZFS version on your Linux installation is greater than or equal to the ZFS version on your FreeNAS installation (with `zpool --version`).

**Comment by Thanatos07** [comment]
Im really sorry for all the trouble and i really appreciate your help. I have freenas 11.3 U4 by the way. Anyways I am now running a live version of mint as i cant seem to mount it on my usb installed parrot OS and it says 1538 files done. Question though, if i run it from the current folder like root/h101na/USMLEStep1 will it only process the files within USMLEStep1?or will it include the folders in USMLEstep1 only?or will it include parent directories as well? Thank you for your time.

**Comment by gary17** [comment]
No problem, we all run into trouble from time to time.

If you run `zfs-recompress.sh` in the current folder, without the `-f, --folder FOLDER` option, it will process `all files in the current working directory and all its descendant directories` (parent folders will not be processed). So, if you run it in `/mnt/h101nas/USMLEStep1/`, it will process all files in `/mnt/h101nas/USMLEStep1/Foo/` as well as `/mnt/h101nas/USMLEStep1/Foo/Bar/`. If you want to process a parent directory (and all its descendant directories), you need to specify the `-f, --folder FOLDER` option.

**Comment by gary17** [comment]
I patched up `zfs-recompress.sh` to support both Linux and FreeBSD/FreeNAS. Tested under FreeBSD 11.3. Please give it a try and let me know if there are any problems with it under FreeNAS.

**Comment by Thanatos07** [comment]
Wow thanks. I'm still running it on my ubuntu as of the moment and its working fine although im doing it by folder as im unable to do it for long times on my laptop. Hopefully everything will work out on freenas and il be able to do the whole thing in the through my nas. That said i noticed that i get increasing disk space usage as of the moment as im doing a large folder now. I'll check on the final space once im done with it. Again, thank you very much for your help. It is very much appreciated.😀

**Comment by Thanatos07** [comment]
I was able to process a folder from lz4 to gzip9. Most of it were media files. Sad thing is my free disk space went down from 750 gigs to 90+ gigs. I tried to change the compression back to lz4 and ran zfs recompress again but its still the same. Now i feel like i just kicked a hard plate. Lol

**Comment by gary17** [comment]
Try searching your storage space for all files with the `tmp` extension. If any of those include a unique identifier in the form of `foo.ebcecd6f-71d4-444d-8070-c3197309b624.tmp`, those might be duplicates created by `zfs-recompress.sh` and never renamed back as originals, due to permission errors, signals, etc. For example, if you have a file named `foo.ebcecd6f-71d4-444d-8070-c3197309b624.tmp` and a file named `foo` and **both have the same `md5sum`**, the `tmp` file can be deleted.
